### ISSUE TITLE
bionic: cannot run bash via qemu-arm-static/qemu-aarch64-static

### ISSUE THREAD

**Issue by nuclearsandwich** [osrf/multiarch-docker-image-generation#18]
The recent bionic sync fixed our glibc issue #17 but bash no longer runs via qemu.

There are several ways to reproduce the issue, the quickest is firing up our existing bionic image, updating the repository and installing the latest bash version from the repos.

During configure you'll see the result

```
bash: xmalloc: .././locale.c:81: cannot allocate 2 bytes (0 bytes allocated)
dpkg: error processing package bash (--configure):
 installed bash package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 bash
W: http: Running in qemu-user, not using seccomp
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@4bd3ec35b0af:/# bash
bash: xmalloc: .././locale.c:81: cannot allocate 2 bytes (0 bytes allocated)
```

You can also reproduce this in an x86_64 bionic container by installing qemu-user-static from the bionic repo, adding the arm64 repos and installing bash as an alternate architecture package. In docker containers binfmt doesn't update and this will uninstall your native bash package. But you can still run `qemu-aarch64-static $(which bash)` from your running shell and see the same error.

Edit: forgot to explicitly mention that this affects qemu 2.10 and qemu 2.11 (from bionic).

**Comment by nuclearsandwich** [comment]
This issue is blocking updated bionic images for armhf and arm64 (FYI @clalancette).

**Comment by nuclearsandwich** [comment]
This is already logged upstream as https://bugs.launchpad.net/ubuntu/+source/bash/+bug/1751011 and it's resolved in debian in a way that Ubuntu isn't "keen" on. I'm going to try putting together an image with the earlier bash package, which still works when the rest of the distro updates.

**Comment by nuclearsandwich** [comment]
bash 4.4.12 has already been purged from ports.ubuntu.com so I can't just pin the package for bionic in the build image script. I think that means the simplest path forward is to build 4.4.18 with -no-pie and sideload it into the image during the bootstrap process. I'm not entirely certain how to do that but I'll start with getting the package built and work from there.

**Comment by nuclearsandwich** [comment]
It looks like the root cause is [this qemu bug](https://bugs.launchpad.net/qemu/+bug/1749393). It hasn't been triaged by the qemu team yet so I don't have any estimate on its upstream resolution. Our position-dependent package will continue to work and be preferred over the upstream package until the next package revision or update, at which point we can explore either pinning our package in the image or updating our package to match upstream but with -no-pie. 

Since we supply vendored binaries for qemu-user-static we can pull an upstream fix from qemu and test it with ease and even deploy it outside of a release cycle.

**Comment by tfoote** [comment]
Subscribed to get updates and increase the "heat" on that bug. It's at least in the top 25 or so by heat rating. Though there are several much higher.

**Comment by nuclearsandwich** [comment]
The bash bug in ubuntu has been assigned wontfix for bionic `rls-bb-notfixing`. There's some folks discussing strategy for how to resolve the qemu issue. As mentioned previously, we can adopt the qemu fix as soon as it's available for testing as we control the qemu-{arm,aarch64}-static binary inclusion for these images outside of any upstream release process.

**Comment by telelaci** [comment]
I don't understand this conversation.
Someone reports a bug:
bash: xmalloc: .././locale.c:81: cannot allocate 2 bytes (0 bytes allocated)

Other guy answers, this has already been reported:
bash: xmalloc: .././shell.c:1709: cannot allocate 10 bytes (0 bytes allocated)

What makes you think this is the same error?

**Comment by nuclearsandwich** [comment]
> What makes you think this is the same error?

There's a substantial bit of evidence that says they're very closely aligned if not _precisely_ the same.
In both cases calls to bash's internal malloc are failing to allocate any memory.

1. Both issues exhibit in similar environments (qemu, bash compiled as a position independent executable) and yield the same error message, albeit in different locations.
2. They have the same workaround: Building bash with -no-pie.
3. At least in the case of my reports, there are several places in the debootstrap process and in testing where the xmalloc errors are printed (basically any time bash is invoked in the qemu environment) and I grabbed a representative example line, not every single instance of the error message.
4. The conversation on the bash bug mailing list proposes a hypothesis as to why this is happening that seems to be substantiated by tests and proposed patches to qemu. https://lists.gnu.org/archive/html/bug-bash/2018-02/msg00080.html which is to say that it's likely both issues will have the same fix.

**Comment by telelaci** [comment]
Your theory is not so good, because a patch has already been comitted to the "...shell.c:1709" malloc bug.
And nothing has happened to the "./locale.c:81:" bug. And from now it will take another 2 weeks, when people slowly discover... wow there was one more (maybe even more) aspect of that bug... here and there. We should fix that too.
Maybe you mistake me, I can see the similarity. But they are different also in the same time, they should be handled separatedly, or the fixing procedure will take a year, if we always assume that they are the same bug.

**Comment by nuclearsandwich** [comment]
> Your theory is not so good, because a patch has already been comitted to the "...shell.c:1709" malloc bug.
> And nothing has happened to the "./locale.c:81:" bug.

Can you show a link to the patch you're referencing that resolves one issue and not the other?

I have seen a patch proposed on the qemu mailing list that attempts to reserve space for the kind of brk/sbrk usage bash's internal malloc would need for PIE binaries. http://lists.nongnu.org/archive/html/qemu-devel/2018-03/msg04700.html which I haven't yet had the time to try so I do not know what use cases it covers.

I also see the "Fix committed" status change on the bash (ubuntu) bug [LP: 1751011](https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1751011) although I don't see an easy way to go from that status change to the actual commit that fixes the issue according to the status update. Looking at https://bugs.launchpad.net/ubuntu/+source/bash/4.4.18-2ubuntu1 it seems that Debian has opted to re-enable building bash without -no-pie and configure it to build without its internal malloc (addition of --without-bash-malloc configuration option, which was suggested as a different workaround) Ubuntu have pulled this configuration and it is currently packaged in bionic-proposed.

I tried it out using the current OSRF image (which is functional with a custom bash built with -no-pie) like so:
```
% docker run -ti osrf/ubuntu_arm64 bash
root@56b9bcd2d6ac:/# qemu-arm-static --version
qemu-arm version 2.10.1(Debian 1:2.10+dfsg-0ubuntu3.1)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
root@56b9bcd2d6ac:/# apt list bash
Listing... Done
bash/now 4.4.18-1ubuntu1osrf1 armhf [installed,local]
N: There is 1 additional version. Please use the '-a' switch to see it
root@56b9bcd2d6ac:/# echo 'deb http://ports.ubuntu.com bionic-proposed main restricted universe multiverse' >> /etc/apt/sources.list
root@56b9bcd2d6ac:/# apt-get update
... output omitted.
root@56b9bcd2d6ac:/# apt-get install bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  bash-doc
Recommended packages:
  bash-completion
The following packages will be upgraded:
  bash
1 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
Need to get 552 kB of archives.
After this operation, 4198 kB disk space will be freed.
Get:1 http://ports.ubuntu.com bionic-proposed/main armhf bash armhf 4.4.18-2ubuntu1 [552 kB]
Fetched 552 kB in 2s (335 kB/s)
(Reading database ... 11018 files and directories currently installed.)
Preparing to unpack .../bash_4.4.18-2ubuntu1_armhf.deb ...
Unpacking bash (4.4.18-2ubuntu1) over (4.4.18-1ubuntu1osrf1) ...
Setting up bash (4.4.18-2ubuntu1) ...
update-alternatives: using /usr/share/man/man7/bash-builtins.7.gz to provide /usr/share/man/man7/builtins.7.gz (builtins.7.gz) in auto mode
W: http: Running in qemu-user, not using seccomp
root@56b9bcd2d6ac:/# bash
root@56b9bcd2d6ac:/# 
```

It took a bit more experimentation but I was also able to adapt the build-image.sh script from this repository to install the bash package from bionic-proposed rather than the ones I built and that was also successful. When this revised package lands in bionic I expect to be able to rebuild our images without any additional mitigations. Of course, I'll continue to follow the upstream qemu bug related to brk/sbrk in position independent executables but the "committed fix" has handled the use cases I've thrown at it so far.

I'll also mention that building and releasing quality free and open source software is a massive undertaking and a collective effort. There will always be bugs and improvements to be made. Negative comments without constructive value may be moderated or removed.

**Comment by telelaci** [comment]
"Negative comments without constructive value may be moderated or removed."
What ? What did you sniff ? Its not my job to fix that package and make it work, I have many other things to do, a lot lot. Deleting my comment will not fix any problem, removing the criticism won't make anyone smarter, doesn't improve any system. Do you live in Russia ? In this thread, the above bug blocks armhf,arm64 development badly, was reported a month ago, some other places even earlier, and still it doesn't work.
And you think outsiders can't criticise that, they can't be negative, only if they suggest a solution. Linux is crap and always will be crap because people who make it are really unprofessional. The thinking is unprofessional.
What will wake some liable people up if no one can criticize the above fact above this bug ? I was not personal at all, neither rude. Who invented the cited "without being constructive" rule ?
In a software firm , anyone who is responsible for such critical bug, and can't fix it in time, would be kicked, fired without hesitation. Their bosses wouldn't try to act in the costructive way but rather in destructive. I hope you know this, don't you. There are liable, responsible people, at least someone is, always. This is why it works.
And this is what doesn't : 
"There will always be bugs and improvements to be made."
How beautiful adage, my grampa couldn't have said better. In the professional world, no one can answer to a specific complaint about a specific bug with a nice adage, to explain the nature of the world. This is not a really professional world, indeed, but at least try to understand why this is an inproper answer to displeasure.

**Comment by tfoote** [comment]
@telelaci Your recent posts in this thread do not follow the ROS guidelines for support. You can read the guideliens at: http://wiki.ros.org/Support As well as the GitHub Community Guidelines: https://help.github.com/articles/github-community-guidelines/

In particular you are using ad hominem arguments and insulting the efforts of and are complaining about how other people are doing their work. These are not appropriate and will not be tolerated. We would appreciate help toward resolving this issue but you need to present it in a way that does not insult or otherwise harass members of our community.

I have remove the parts that are unrelated to this issue. Please stay on topic and only provide technical information in a professional manner in the future.

**Comment by nuclearsandwich** [comment]
Although the [qemu issue](https://bugs.launchpad.net/qemu/+bug/1749393) is still outstanding, the workaround applied by both Debian and Ubuntu, building bash without its internal malloc, appears to work for our purposes.

New images have been published for osrf/ubuntu_arm64:bionic and osrf/ubuntu_armhf:bionic which are free of our modifications.
